### ISSUE TITLE
TypeError while trying to save

### ISSUE THREAD

**Issue by AdelaideSky** [SnowpMakes/omori-apple-silicon#1]
Hay ! I don't know at all if it's related to the patch but as i never got the problem on non-m1/non-patched versions, imma give it a shot...

My friend who uses an m1 machine started playing and as the game didn't launched i made him install the patch, though, after 2 hours of gameplay, when trying to (finally help) save, we got the error:

```
UnknownError
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of type Buffer, TypedArray or DataView. Received type number (0)
```
Here's a screen of what shows up on screen:
![image](https://github.com/SnowpMakes/omori-apple-silicon/assets/63637808/d15ffce8-6872-4f5c-9756-a4516d301ee3)

We tried multiple times and the error still appears. Though, it is important to notice that the game still saves! We were able to load the game normally after a restart (as you can't do anything after the error appeared).

As it's not really critical it's not that urgent, and i really don't think it's the patch directly, though updating something maybe broke some function or something... 

Thanks for your time working on this!!

**Comment by SnowpMakes** [comment]
Hi!

I knew I forgot something..
I created the technique behind this patch months before the actual scrips, and I just knew I missed something.
This happens when - spoiler alert - later in the game you need a different title screen, eg. Blackspace or Post-credits, as there's a mistake in the saving code. I never got around to solving it without decrypting the game files, which is hard to do.

I'll look into it over the coming days. Thanks for reporting it!

**Comment by AdelaideSky** [comment]
You're welcome and thanks for the explanation ! 
Take your time: as i said it's not blocking (just as you said a titlescreen not updated but it's not that bad) :D
